export const CONSTRUCTOR_ADD: 'CONSTRUCTOR_ADD' = 'CONSTRUCTOR_ADD';
export const CONSTRUCTOR_DEL: 'CONSTRUCTOR_DEL' = 'CONSTRUCTOR_DEL';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR_RESET' = 'CONSTRUCTOR_RESET';
export const CONSTRUCTOR_REPLACE: 'CONSTRUCTOR_REPLACE' = 'CONSTRUCTOR_REPLACE';
