export const INGREDIENTS_REQUEST: 'INGREDIENTS_REQUEST' = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_SUCCESS: 'INGREDIENTS_SUCCESS' = 'INGREDIENTS_SUCCESS';
export const INGREDIENTS_FAILURE: 'INGREDIENTS_FAILURE' = 'INGREDIENTS_FAILURE';

export const INGREDIENTS_SET_TAB: 'INGREDIENTS_SET_TAB' = 'INGREDIENTS_SET_TAB';
